// BIC charts in a plain React app — no Power BI anywhere in the stack.
//
// What this page proves:
//   • Chart code generated by the BIC backend runs unmodified in a third-party host.
//   • The runtime (@bicharts/chart-host) is the SAME one the Power BI visual uses for options
//     resolution, geometry, and the cross-filter grammar — not a reimplementation.
//   • Cross-chart filtering works: click a bubble, the table filters to that city.
//   • Live restyle works without regenerating: the slider changes the plotted-point cap
//     and the chart repaints (and says so on-chart when it truncates).
//
// At RUN time there is no BIC dependency at all: no API key, no network call, no per-render
// cost. The charts are committed source; see src/charts/index.ts for their provenance.
import { useMemo, useState } from 'react';
import * as d3 from 'd3';
import { ingest } from '@bicharts/shape-core/ingest';
import { BicChart, BicChartGroup, useBicSelection } from '@bicharts/chart-host/react';
import { naBubblesCode, cityTableCode, naBubblesGeo } from './charts';
// The app owns its own data, exactly as a real consumer would — this is a copy of
// testharness/datasets/na_city_metrics.csv, the same file the charts were generated from.
import cityCsv from './data/na_city_metrics.csv?raw';
import './App.css';

// ONE source table, shared by both charts. BicChartGroup derives each chart's payload from
// it and keeps the payload-row -> source-row map, which is what makes a click in the map
// select the RIGHT rows in the table (payload indices re-base when rows are filtered).
// ONE CALL. This used to be a CSV parse plus six hand-written column descriptors, each
// asserting a dataType and a measure/dimension role by hand — facts the profiler derives
// from the data itself. Hand-maintained metadata beside real data is metadata that goes
// stale: add a column to the CSV and the old version drew a chart that silently ignored it.
//
// `ingest` is the shared front door (@bicharts/shape-core), the same measurement engine the
// Power BI visual feeds. It returns the MEASURED shape and rows keyed by column name, which
// is exactly what BicChartGroup wants — so there is no adapter between the data source and
// the chart.
//
// dedup defaults to TRUE and is left on here: this is a metrics table, one row per city, so
// there is nothing to collapse, and shape fidelity is what a chart wants. A caller whose
// result rows must line up one-to-one with source rows (or where repetition is itself the
// signal) passes { dedup: false }.
function useCityData() {
    return useMemo(() => ingest({ kind: 'csv', text: cityCsv }), []);
}

// The toolbar lives INSIDE the group so it can read and clear the shared selection.
function Toolbar({ maxMapPoints, setMaxMapPoints }:
                 { maxMapPoints: number; setMaxMapPoints: (n: number) => void }) {
    const sel = useBicSelection();
    return (
        <section className="controls">
            <label>
                Max map points: <strong>{maxMapPoints}</strong>
                <input
                    type="range" min={1} max={25} value={maxMapPoints > 25 ? 25 : maxMapPoints}
                    onChange={e => setMaxMapPoints(Number(e.target.value))}
                />
            </label>
            <span className="hint">
                Live restyle — the chart re-renders and annotates the truncation itself.
                Nothing is regenerated.
            </span>
            <button onClick={sel.clear} disabled={!sel.rows.length}>
                {sel.rows.length ? `Clear selection (${sel.rows.length})` : 'Clear selection'}
            </button>
        </section>
    );
}

// Per-chart caption: says what a chart is showing, and which sibling did it. `me` is the
// chart's own id, so the ORIGIN chart reads "you picked N" while the other reads "filtered".
function Caption({ me, idle }: { me: string; idle: string }) {
    const sel = useBicSelection();
    if (!sel.rows.length) return <p className="sub">{idle}</p>;
    return (
        <p className="sub">
            {sel.sourceId === me
                ? `${sel.rows.length} selected here — click it again, or click empty space, to clear.`
                : `Filtered to ${sel.rows.length} row(s) selected in the ${sel.sourceId}.`}
        </p>
    );
}

export default function App() {
    const { rows, columns } = useCityData();
    const [maxMapPoints, setMaxMapPoints] = useState(1000);

    // Options are PLAIN DATA. Changing them calls setOptions() on the live host — a
    // repaint, never a recompile and never a regeneration.
    const mapOptions = useMemo(() => ({
        width: 900, height: 520,
        themeFg: '#252423', themeAccent: '#118dff',
        allowTooltips: true,
        maxMapPoints,
    }), [maxMapPoints]);

    const tableOptions = useMemo(() => ({
        width: 900, height: 420,
        themeFg: '#252423', themeAccent: '#118dff',
        allowTooltips: true,
    }), []);

    return (
        <main className="bic-demo">
            <header>
                <h1>BIC charts in React</h1>
                <p>
                    Two charts generated by the BIC backend through the MCP server, committed to
                    this repo as source, running in a plain Vite + React app. No Power BI, and no
                    BIC call at run time.
                </p>
            </header>

            <BicChartGroup rows={rows} columns={columns}>
                <Toolbar maxMapPoints={maxMapPoints} setMaxMapPoints={setMaxMapPoints} />

                <section className="chart-block">
                    <h2>North America (Bubbles)</h2>
                    <Caption me="map" idle="Click a city to filter the table below." />
                    <BicChart
                        id="map"
                        code={naBubblesCode}
                        d3={d3}
                        options={{ ...mapOptions, geo: naBubblesGeo }}
                        className="chart"
                    />
                </section>

                <section className="chart-block">
                    <h2>Tabular with embedded</h2>
                    <Caption me="table" idle="Click a row to filter the map above." />
                    <BicChart
                        id="table"
                        code={cityTableCode}
                        d3={d3}
                        options={tableOptions}
                        className="chart"
                    />
                </section>
            </BicChartGroup>

            <footer>
                <p>
                    Provenance: both charts were produced by <code>generate_chart</code> against the
                    BIC backend on 2026-07-25 and written into <code>src/charts/</code>. Regenerate
                    with the same <code>out_dir</code> to update them.
                </p>
            </footer>
        </main>
    );
}

