// BIC charts in a plain React app — no Power BI anywhere in the stack.
//
// What this page proves:
//   • Chart code generated by the BIC backend runs unmodified in a third-party host.
//   • The runtime (@bicharts/chart-host) is the SAME one the Power BI visual uses for options
//     resolution, geometry, and the cross-filter grammar — not a reimplementation.
//   • Cross-chart filtering works: click a bubble, the table filters to that city.
//   • Live restyle works without regenerating: the slider changes the plotted-point cap
//     and the chart repaints (and says so on-chart when it truncates).
//
// At RUN time there is no BIC dependency at all: no API key, no network call, no per-render
// cost. The charts are committed source; see src/charts/index.ts for their provenance.
import { useMemo, useState } from 'react';
import * as d3base from 'd3';
import * as d3Sankey from 'd3-sankey';
import * as d3Hexbin from 'd3-hexbin';
// Plugins outside d3 v7 core. The visual CDN-loads these and the Excel add-in bundles
// them; without them a Sankey or hexbin chart dies on 'd3.sankey is not a function'.
// A spread also makes the result EXTENSIBLE - a module namespace is frozen, and a
// generated chart installs its own d3.llm* helpers onto whatever d3 it is handed.
//
// MERMAID IS DELIBERATELY NOT HERE. A Mermaid diagram needs the library on this same object
// (`Object.assign(d3, { mermaid })` after `import mermaid from 'mermaid'`), but it is about a
// megabyte and none of this app's committed charts is a diagram, so importing it would be a
// download nothing uses. The general mechanism is the point rather than this list: call
// `requiredD3Plugins(code)` from @bicharts/chart-host and it names every package a given
// chart needs BEFORE the chart runs, which is how a real consumer decides what to install.
const d3 = { ...d3base, ...d3Sankey, ...d3Hexbin };
import { ingest } from '@bicharts/shape-core/ingest';
import { BicChart, BicChartGroup, useBicSelection } from '@bicharts/chart-host/react';
import { naBubblesCode, cityTableCode, naBubblesGeo } from './charts';
// The app owns its own data, exactly as a real consumer would — this is a copy of the
// 42-row city-metrics CSV the charts were generated from.
import cityCsv from './data/na_city_metrics.csv?raw';
import './App.css';

// ONE source table, shared by both charts. BicChartGroup derives each chart's payload from
// it and keeps the payload-row -> source-row map, which is what makes a click in the map
// select the RIGHT rows in the table (payload indices re-base when rows are filtered).
// ONE CALL. This used to be a CSV parse plus six hand-written column descriptors, each
// asserting a dataType and a measure/dimension role by hand — facts the profiler derives
// from the data itself. Hand-maintained metadata beside real data is metadata that goes
// stale: add a column to the CSV and the old version drew a chart that silently ignored it.
//
// `ingest` is the shared front door (@bicharts/shape-core), the same measurement engine the
// Power BI visual feeds. It returns the MEASURED shape and rows keyed by column name, which
// is exactly what BicChartGroup wants — so there is no adapter between the data source and
// the chart.
//
// dedup defaults to TRUE and is left on here: this is a metrics table, one row per city, so
// there is nothing to collapse, and shape fidelity is what a chart wants. A caller whose
// result rows must line up one-to-one with source rows (or where repetition is itself the
// signal) passes { dedup: false }.
function useCityData() {
    return useMemo(() => ingest({ kind: 'csv', text: cityCsv }), []);
}

// The toolbar lives INSIDE the group so it can read and clear the shared selection.
function Toolbar({ maxMapPoints, setMaxMapPoints, labelContrast, setLabelContrast }:
                 { maxMapPoints: number; setMaxMapPoints: (n: number) => void;
                   labelContrast: boolean; setLabelContrast: (on: boolean) => void }) {
    const sel = useBicSelection();
    return (
        <section className="controls">
            <label>
                Max map points: <strong>{maxMapPoints}</strong>
                <input
                    type="range" min={1} max={25} value={maxMapPoints > 25 ? 25 : maxMapPoints}
                    onChange={e => setMaxMapPoints(Number(e.target.value))}
                />
            </label>
            <span className="hint">
                Live restyle — the chart re-renders and annotates the truncation itself.
                Nothing is regenerated.
            </span>
            {/* The visual's label-contrast fail-safe, shared: chart-host runs it after every
                render (on by default). A page that owns its label colours turns it off here;
                the prop is the same switch the Excel add-in and the Power BI visual expose. */}
            <label>
                <input
                    type="checkbox" checked={labelContrast}
                    onChange={e => setLabelContrast(e.target.checked)}
                />
                {' '}Fix hard-to-read labels
            </label>
            <button onClick={sel.clear} disabled={!sel.rows.length}>
                {sel.rows.length ? `Clear selection (${sel.rows.length})` : 'Clear selection'}
            </button>
        </section>
    );
}

// Per-chart caption: says what a chart is showing, and which sibling did it. `me` is the
// chart's own id, so the ORIGIN chart reads "you picked N" while the other reads "filtered".
function Caption({ me, idle }: { me: string; idle: string }) {
    const sel = useBicSelection();
    if (!sel.rows.length) return <p className="sub">{idle}</p>;
    return (
        <p className="sub">
            {sel.sourceId === me
                ? `${sel.rows.length} selected here — click it again, or click empty space, to clear.`
                : `Filtered to ${sel.rows.length} row(s) selected in the ${sel.sourceId}.`}
        </p>
    );
}

export default function App() {
    const { rows, columns } = useCityData();
    const [maxMapPoints, setMaxMapPoints] = useState(1000);
    // On by default, as in every host. A prop, not an option: it governs a pass the host runs
    // AFTER a render, so flipping it tears the host down and rebuilds (code identity is
    // unchanged; only the config is) - a checkbox, not a live restyle.
    const [labelContrast, setLabelContrast] = useState(true);

    // Options are PLAIN DATA. Changing them calls setOptions() on the live host — a
    // repaint, never a recompile and never a regeneration.
    const mapOptions = useMemo(() => ({
        width: 900, height: 520,
        themeFg: '#252423', themeAccent: '#118dff',
        allowTooltips: true,
        maxMapPoints,
    }), [maxMapPoints]);

    const tableOptions = useMemo(() => ({
        width: 900, height: 420,
        themeFg: '#252423', themeAccent: '#118dff',
        allowTooltips: true,
    }), []);

    return (
        <main className="bic-demo">
            <header>
                <h1>RegiaBI charts in React</h1>
                <p>
                    Two charts generated by RegiaBI through its MCP server, committed to this
                    repo as source, running in a plain Vite + React app. No Power BI, and no call
                    to us at run time.
                    {' '}<a href="https://bizintelligencechampions.com/regiabi/developers?loc=ghdemo">RegiaBI for developers</a>
                    {' '}&middot;{' '}
                    <a href="https://github.com/codexguy/bicharts-react-demo">Source</a>
                </p>
            </header>

            <BicChartGroup rows={rows} columns={columns}>
                <Toolbar maxMapPoints={maxMapPoints} setMaxMapPoints={setMaxMapPoints}
                         labelContrast={labelContrast} setLabelContrast={setLabelContrast} />

                <section className="chart-block">
                    <h2>North America (Bubbles)</h2>
                    <Caption me="map" idle="Click a city to filter the table below." />
                    <BicChart
                        id="map"
                        code={naBubblesCode}
                        d3={d3}
                        options={{ ...mapOptions, geo: naBubblesGeo }}
                        labelContrast={labelContrast}
                        className="chart"
                    />
                </section>

                <section className="chart-block">
                    <h2>Tabular with embedded</h2>
                    <Caption me="table" idle="Click a row to filter the map above." />
                    <BicChart
                        id="table"
                        code={cityTableCode}
                        d3={d3}
                        options={tableOptions}
                        labelContrast={labelContrast}
                        className="chart"
                    />
                </section>
            </BicChartGroup>

            <footer>
                <p>
                    Provenance: both charts were produced by <code>generate_chart</code> against the
                    RegiaBI engine on 2026-07-25 and written into <code>src/charts/</code>. Regenerate
                    with the same <code>out_dir</code> to update them.
                </p>
            </footer>
        </main>
    );
}

